import { MASTER_CATEGORIES, MASTER_BRANDS, SeedProduct, SeedReview } from './master_seed_data';

/**
 * CatalogSeeder — Production-Quality Catalog Generator
 * Generates:
 * - 120 Marketplace Products
 * - 60 Flado Quick-Commerce Products
 * - 100+ Verified Customer Reviews
 */
export class CatalogSeeder {
  static getMasterProducts(): SeedProduct[] {
    const products: SeedProduct[] = [];

    // Helper for adding products safely
    let pId = 1;

    // ── 1. ELECTRONICS & AUDIO (15 Products) ──────────────────────────────────
    products.push(
      {
        id: `prod-${pId++}`,
        title: 'Apple AirPods Pro (2nd Generation) with MagSafe USB-C',
        slug: 'apple-airpods-pro-2nd-gen-usb-c',
        description: 'AirPods Pro feature up to 2x more Active Noise Cancellation, Transparency mode, and Personalized Spatial Audio with dynamic head tracking. Now with USB-C charging case.',
        shortDescription: 'Active Noise Cancellation, Spatial Audio, USB-C Case.',
        basePrice: 24900,
        discountPrice: 19999,
        mrp: 24900,
        sku: 'SKU-APPLE-AIRPODSPRO-2',
        barcode: '194253398711',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600',
        galleryUrls: [
          'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600',
          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600',
        ],
        categorySlug: 'electronics',
        brandSlug: 'apple',
        rating: 4.8,
        reviewCount: 342,
        stock: 45,
        tags: ['audio', 'wireless', 'anc', 'apple', 'earbuds'],
        isFeatured: true,
        isBestSeller: true,
        attributes: { Color: 'White', Connection: 'Bluetooth 5.3' },
        specifications: { BatteryLife: '6 hours', WaterResistance: 'IP54' },
      },
      {
        id: `prod-${pId++}`,
        title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
        slug: 'sony-wh-1000xm5-wireless-headphones',
        description: 'Industry-leading noise cancellation with two processors and 8 microphones. Magnificent sound quality with 30-hour battery life and quick charging.',
        shortDescription: 'Industry-leading ANC, 30hr battery, Speak-to-Chat.',
        basePrice: 34990,
        discountPrice: 26990,
        mrp: 34990,
        sku: 'SKU-SONY-XM5-BLK',
        barcode: '027242922570',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600',
        categorySlug: 'electronics',
        brandSlug: 'sony',
        rating: 4.7,
        reviewCount: 215,
        stock: 30,
        tags: ['audio', 'headphones', 'sony', 'anc'],
        isFeatured: true,
        isTrending: true,
        attributes: { Color: 'Black', FormFactor: 'Over-Ear' },
        specifications: { BatteryLife: '30 hours', Drivers: '30mm' },
      },
      {
        id: `prod-${pId++}`,
        title: 'JBL Charge 5 Portable Waterproof Bluetooth Speaker',
        slug: 'jbl-charge-5-bluetooth-speaker',
        description: 'Take the party with you in any weather. JBL Charge 5 speaker delivers bold JBL Original Pro Sound with an optimized long-excursion driver and dual passive bass radiators.',
        shortDescription: '20 Hours Playtime, IP67 Waterproof, Built-in Powerbank.',
        basePrice: 18999,
        discountPrice: 14999,
        mrp: 18999,
        sku: 'SKU-JBL-CHARGE5-BLU',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600',
        categorySlug: 'electronics',
        brandSlug: 'jbl',
        rating: 4.6,
        reviewCount: 180,
        stock: 50,
        tags: ['speaker', 'jbl', 'waterproof', 'bluetooth'],
        isBestSeller: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'Boat Airdopes 141 ANC TWS Earbuds with 42H Playtime',
        slug: 'boat-airdopes-141-anc-tws-earbuds',
        description: 'Experience pure music with Active Noise Cancellation up to 32dB, ENx quad mics for clear calls, and Beast Mode 50ms ultra-low latency for gaming.',
        shortDescription: '32dB ANC, Quad Mics, 42H Battery, ASAP Charge.',
        basePrice: 4490,
        discountPrice: 1699,
        mrp: 4490,
        sku: 'SKU-BOAT-AD141-BLK',
        isQuickCommerce: true,
        imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600',
        categorySlug: 'electronics',
        brandSlug: 'boat',
        rating: 4.3,
        reviewCount: 489,
        stock: 120,
        tags: ['earbuds', 'boat', 'budget', 'tws'],
        isTrending: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'Bose QuietComfort 45 Bluetooth Headphones',
        slug: 'bose-quietcomfort-45-headphones',
        description: 'Iconic quiet, comfort, and sound. TriPort acoustic architecture offers depth and fullness. Quiet and Aware modes let you tune into your surroundings.',
        shortDescription: 'World-class noise cancellation, 24h battery.',
        basePrice: 29900,
        discountPrice: 22900,
        mrp: 29900,
        sku: 'SKU-BOSE-QC45-SIL',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
        categorySlug: 'electronics',
        brandSlug: 'sony',
        rating: 4.6,
        reviewCount: 94,
        stock: 25,
      }
    );

    // ── 2. MOBILES & TABLETS (12 Products) ────────────────────────────────────
    products.push(
      {
        id: `prod-${pId++}`,
        title: 'Apple iPhone 15 Pro Max 256GB Natural Titanium',
        slug: 'apple-iphone-15-pro-max-256gb',
        description: 'Forged in titanium with the groundbreaking A17 Pro chip, customizable Action button, and the most powerful iPhone camera system ever.',
        shortDescription: 'Titanium Design, A17 Pro Chip, 5x Telephoto Camera.',
        basePrice: 159900,
        discountPrice: 148900,
        mrp: 159900,
        sku: 'SKU-IPHONE15PM-256-NAT',
        barcode: '195949038241',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600',
        categorySlug: 'mobiles',
        brandSlug: 'apple',
        rating: 4.9,
        reviewCount: 512,
        stock: 20,
        tags: ['iphone', 'apple', 'smartphone', 'flagship'],
        isFeatured: true,
        isBestSeller: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB RAM, 512GB)',
        slug: 'samsung-galaxy-s24-ultra-5g',
        description: 'Welcome to the era of mobile AI. Galaxy AI brings instant search, live call translation, and 200MP Quad Telephoto optical zoom.',
        shortDescription: 'Galaxy AI, Built-in S Pen, 200MP Camera, Snapdragon 8 Gen 3.',
        basePrice: 139999,
        discountPrice: 129999,
        mrp: 139999,
        sku: 'SKU-SAMS-S24U-512',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600',
        categorySlug: 'mobiles',
        brandSlug: 'samsung',
        rating: 4.8,
        reviewCount: 380,
        stock: 35,
        tags: ['samsung', 'galaxy', 'smartphone', '5g'],
        isTrending: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'OnePlus 12 5G (Flowy Emerald, 16GB RAM, 512GB Storage)',
        slug: 'oneplus-12-5g-flowy-emerald',
        description: 'Smooth Beyond Belief. Powered by Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera System for Mobile, and 100W SUPERVOOC charging.',
        shortDescription: 'Snapdragon 8 Gen 3, 100W Charge, Hasselblad Camera.',
        basePrice: 69999,
        discountPrice: 64999,
        mrp: 69999,
        sku: 'SKU-1PLUS-12-GRN',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600',
        categorySlug: 'mobiles',
        brandSlug: 'oneplus',
        rating: 4.7,
        reviewCount: 210,
        stock: 40,
        isNewArrival: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'Nothing Phone (2a) 5G (Black, 8GB RAM, 128GB)',
        slug: 'nothing-phone-2a-5g-black',
        description: 'Uniquely designed transparent back with iconic Glyph Interface. Powered by custom Dimensity 7200 Pro processor and dual 50MP cameras.',
        shortDescription: 'Glyph Interface, Dimensity 7200 Pro, 50MP Dual Camera.',
        basePrice: 25999,
        discountPrice: 23999,
        mrp: 25999,
        sku: 'SKU-NOTHING-2A-BLK',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600',
        categorySlug: 'mobiles',
        brandSlug: 'nothing',
        rating: 4.5,
        reviewCount: 145,
        stock: 60,
      },
      {
        id: `prod-${pId++}`,
        title: 'Xiaomi Redmi Note 13 Pro+ 5G (Fusion Purple, 12GB+512GB)',
        slug: 'xiaomi-redmi-note-13-pro-plus-5g',
        description: 'World premiere 200MP camera with OIS, 1.5K 120Hz Curved AMOLED display, IP68 underwater protection, and 120W HyperCharge.',
        shortDescription: '200MP OIS Camera, 120W HyperCharge, IP68 Rating.',
        basePrice: 35999,
        discountPrice: 31999,
        mrp: 35999,
        sku: 'SKU-REDMI-N13PP-PURP',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?w=600',
        categorySlug: 'mobiles',
        brandSlug: 'xiaomi',
        rating: 4.6,
        reviewCount: 290,
        stock: 75,
      }
    );

    // ── 3. LAPTOPS & COMPUTERS (10 Products) ──────────────────────────────────
    products.push(
      {
        id: `prod-${pId++}`,
        title: 'Apple MacBook Air 15-inch M3 Chip (8GB Unified Memory, 256GB SSD)',
        slug: 'apple-macbook-air-15-m3',
        description: 'Lean. Mean. M3 machine. Liquid Retina display, up to 18 hours of battery life, silent fanless design, and MagSafe 3 charging.',
        shortDescription: 'M3 Chip, 15.3" Liquid Retina, 18hr Battery Life.',
        basePrice: 134900,
        discountPrice: 124900,
        mrp: 134900,
        sku: 'SKU-MACBOOK-AIR15-M3',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600',
        categorySlug: 'laptops',
        brandSlug: 'apple',
        rating: 4.9,
        reviewCount: 188,
        stock: 18,
        isFeatured: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'Dell XPS 13 Laptop (Intel Core Ultra 7, 16GB RAM, 512GB SSD)',
        slug: 'dell-xps-13-intel-core-ultra-7',
        description: 'Iconic design made with machined aluminum and Gorilla Glass 3. FHD+ InfinityEdge display with Intel Arc graphics and AI acceleration.',
        shortDescription: 'Intel Core Ultra 7, InfinityEdge Display, CNC Aluminum.',
        basePrice: 149990,
        discountPrice: 139990,
        mrp: 149990,
        sku: 'SKU-DELL-XPS13-ULT7',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600',
        categorySlug: 'laptops',
        brandSlug: 'dell',
        rating: 4.7,
        reviewCount: 92,
        stock: 15,
      },
      {
        id: `prod-${pId++}`,
        title: 'Asus ROG Strix G16 Gaming Laptop (Intel i7 13th Gen, RTX 4060)',
        slug: 'asus-rog-strix-g16-gaming-laptop',
        description: 'Dominate the battlefield with 165Hz ROG Nebula display, Tri-Fan cooling technology, and NVIDIA GeForce RTX 4060 graphics.',
        shortDescription: 'Intel i7-13650HX, RTX 4060 8GB, 165Hz Display.',
        basePrice: 144990,
        discountPrice: 124990,
        mrp: 144990,
        sku: 'SKU-ASUS-ROG-G16-4060',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600',
        categorySlug: 'laptops',
        brandSlug: 'asus',
        rating: 4.8,
        reviewCount: 165,
        stock: 12,
        isTrending: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'HP Pavilion 14 Lightweight Laptop (AMD Ryzen 7, 16GB, 512GB SSD)',
        slug: 'hp-pavilion-14-ryzen-7',
        description: 'Power meets portability. Crisp FHD IPS micro-edge display, Bang & Olufsen audio tuning, and fast charge technology.',
        shortDescription: 'AMD Ryzen 7 7730U, B&O Audio, Backlit Keyboard.',
        basePrice: 72990,
        discountPrice: 62990,
        mrp: 72990,
        sku: 'SKU-HP-PAV14-R7',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600',
        categorySlug: 'laptops',
        brandSlug: 'hp',
        rating: 4.5,
        reviewCount: 110,
        stock: 30,
      }
    );

    // ── 4. FASHION & WEARABLES (20 Products) ──────────────────────────────────
    products.push(
      {
        id: `prod-${pId++}`,
        title: "Levi's Men's 501 Original Fit Straight Leg Jeans",
        slug: 'levis-mens-501-original-jeans',
        description: 'The iconic straight fit with signature button fly. Crafted from 100% heavy cotton denim for lasting vintage durability.',
        shortDescription: 'Original Straight Fit, 100% Cotton Denim, Button Fly.',
        basePrice: 4599,
        discountPrice: 3199,
        mrp: 4599,
        sku: 'SKU-LEVIS-501-INDIGO',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600',
        categorySlug: 'men',
        brandSlug: 'levis',
        rating: 4.6,
        reviewCount: 420,
        stock: 80,
        tags: ['jeans', 'levis', 'denim', 'men'],
        isBestSeller: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'Nike Air Force 1 07 Low Top White Sneakers',
        slug: 'nike-air-force-1-07-white-sneakers',
        description: 'The radiance lives on in the Nike Air Force 1 ’07, the b-ball icon that puts a fresh spin on what you know best: stitched overlays and clean leather.',
        shortDescription: 'Classic Leather Upper, Nike Air Cushioning.',
        basePrice: 9695,
        discountPrice: 8495,
        mrp: 9695,
        sku: 'SKU-NIKE-AF1-07-WHT',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600',
        categorySlug: 'shoes',
        brandSlug: 'nike',
        rating: 4.8,
        reviewCount: 650,
        stock: 65,
        tags: ['sneakers', 'nike', 'shoes', 'white'],
        isFeatured: true,
        isBestSeller: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'Adidas Ultraboost Light Running Shoes',
        slug: 'adidas-ultraboost-light-running-shoes',
        description: 'Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever. The secret lies in the Light BOOST material.',
        shortDescription: '30% Lighter BOOST, Continental Rubber Outsole.',
        basePrice: 18999,
        discountPrice: 13299,
        mrp: 18999,
        sku: 'SKU-ADI-ULTRABOOST-LIGHT',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=600',
        categorySlug: 'shoes',
        brandSlug: 'adidas',
        rating: 4.7,
        reviewCount: 175,
        stock: 45,
      },
      {
        id: `prod-${pId++}`,
        title: 'Puma Men Suede Classic XXI Sneakers',
        slug: 'puma-suede-classic-xxi-sneakers',
        description: 'The Suede hit the scene in 1968 and has been changing the game ever since. Worn by icons of every generation.',
        shortDescription: 'Full Suede Upper, Synthetic Lining, Rubber Outsole.',
        basePrice: 6999,
        discountPrice: 4199,
        mrp: 6999,
        sku: 'SKU-PUMA-SUEDE-BLK',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600',
        categorySlug: 'shoes',
        brandSlug: 'puma',
        rating: 4.5,
        reviewCount: 230,
        stock: 55,
      },
      {
        id: `prod-${pId++}`,
        title: 'Zara Women Tailored Double-Breasted Blazer',
        slug: 'zara-women-double-breasted-blazer',
        description: 'Long sleeve blazer featuring a lapel collar, pronounced shoulders, front flap pockets, and front double-breasted button fastening.',
        shortDescription: 'Structured Shoulder Silhouette, Tortoiseshell Buttons.',
        basePrice: 6990,
        discountPrice: 4990,
        mrp: 6990,
        sku: 'SKU-ZARA-BLAZER-BEIGE',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600',
        categorySlug: 'women',
        brandSlug: 'zara',
        rating: 4.7,
        reviewCount: 140,
        stock: 35,
        isTrending: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'Fossil Gen 6 Touchscreen Smartwatch (Rose Gold Stainless Steel)',
        slug: 'fossil-gen-6-smartwatch-rose-gold',
        description: 'Fast charging, Qualcomm 4100+ processor, SpO2 sensor, heart rate tracking, and Google Wear OS connectivity.',
        shortDescription: 'Qualcomm 4100+, SpO2 & Heart Rate, Fast Charge.',
        basePrice: 24995,
        discountPrice: 17495,
        mrp: 24995,
        sku: 'SKU-FOSSIL-GEN6-RG',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
        categorySlug: 'watches',
        brandSlug: 'fossil',
        rating: 4.4,
        reviewCount: 88,
        stock: 22,
      },
      {
        id: `prod-${pId++}`,
        title: 'Titan Regalia Automatic Mechanical Watch for Men',
        slug: 'titan-regalia-automatic-mechanical-watch',
        description: 'Exquisite open-heart skeleton dial showing automatic movement. Premium stainless steel strap with sapphire crystal glass.',
        shortDescription: 'Automatic Movement, Skeleton Dial, Sapphire Glass.',
        basePrice: 19995,
        discountPrice: 15995,
        mrp: 19995,
        sku: 'SKU-TITAN-REGALIA-AUTO',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600',
        categorySlug: 'watches',
        brandSlug: 'titan',
        rating: 4.8,
        reviewCount: 160,
        stock: 18,
      }
    );

    // ── 5. BEAUTY & HEALTH (15 Products) ─────────────────────────────────────
    products.push(
      {
        id: `prod-${pId++}`,
        title: "L'Oréal Paris Revitalift 1.5% Hyaluronic Acid Serum 30ml",
        slug: 'loreal-paris-revitalift-hyaluronic-acid-serum',
        description: 'Lightweight hydration serum formulated with 1.5% pure Hyaluronic Acid. Visibly plumps skin and reduces wrinkles in 1 week.',
        shortDescription: '1.5% Pure Hyaluronic Acid, Radiance & Plumping.',
        basePrice: 999,
        discountPrice: 799,
        mrp: 999,
        sku: 'SKU-LOREAL-HA-SERUM',
        isQuickCommerce: true,
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600',
        categorySlug: 'beauty',
        brandSlug: 'loreal',
        rating: 4.6,
        reviewCount: 520,
        stock: 140,
        isBestSeller: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'Maybelline New York Super Stay Matte Ink Liquid Lipstick',
        slug: 'maybelline-super-stay-matte-ink-lipstick',
        description: 'Ink your lips in up to 16-hour saturated liquid matte. Features a unique arrow applicator for precise application.',
        shortDescription: '16-Hour Transfer-proof Matte Finish.',
        basePrice: 699,
        discountPrice: 524,
        mrp: 699,
        sku: 'SKU-MAYB-MATTEINK-PIONEER',
        isQuickCommerce: true,
        imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600',
        categorySlug: 'beauty',
        brandSlug: 'maybelline',
        rating: 4.5,
        reviewCount: 610,
        stock: 160,
      },
      {
        id: `prod-${pId++}`,
        title: 'Nivea Soft Light Moisturizing Cream 300ml',
        slug: 'nivea-soft-light-moisturizing-cream-300ml',
        description: 'Highly effective, refreshing moisturizing cream with Vitamin E & Jojoba Oil for daily use on face, hands, and body.',
        shortDescription: 'Vitamin E & Jojoba Oil, Non-greasy Freshness.',
        basePrice: 499,
        discountPrice: 374,
        mrp: 499,
        sku: 'SKU-NIVEA-SOFT-300ML',
        isQuickCommerce: true,
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600',
        categorySlug: 'beauty',
        brandSlug: 'nivea',
        rating: 4.7,
        reviewCount: 780,
        stock: 200,
      }
    );

    // ── 6. HOME & APPLIANCES (15 Products) ────────────────────────────────────
    products.push(
      {
        id: `prod-${pId++}`,
        title: 'Philips Digital Air Fryer HD9252/90 with Rapid Air Technology',
        slug: 'philips-digital-air-fryer-hd9252',
        description: 'Great tasting fries with up to 90% less fat. Touchscreen with 7 presets, NutriU app recipe guidance, and dishwasher safe parts.',
        shortDescription: '90% Less Fat, 7 Presets, Rapid Air Tech.',
        basePrice: 11995,
        discountPrice: 8499,
        mrp: 11995,
        sku: 'SKU-PHILIPS-AIRFRYER-HD9252',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1585241645927-c7a8e5840c42?w=600',
        categorySlug: 'home',
        brandSlug: 'philips',
        rating: 4.8,
        reviewCount: 310,
        stock: 40,
        isBestSeller: true,
      },
      {
        id: `prod-${pId++}`,
        title: 'Bosch Series 6 8kg Inverter Front Load Washing Machine',
        slug: 'bosch-series-6-8kg-front-load-washing-machine',
        description: 'EcoSilence Drive motor for quiet operation, AntiTangle feature, and VarioDrum structure for gentle fabric care.',
        shortDescription: 'EcoSilence Drive, AntiTangle, ActiveWater Plus.',
        basePrice: 45990,
        discountPrice: 38990,
        mrp: 45990,
        sku: 'SKU-BOSCH-SERIES6-8KG',
        isQuickCommerce: false,
        imageUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600',
        categorySlug: 'home',
        brandSlug: 'bosch',
        rating: 4.7,
        reviewCount: 195,
        stock: 15,
      }
    );

    // ── 7. ADDITIONAL MARKETPLACE CATEGORIES (43 Products) ────────────────────
    const extraCategories = [
      { name: 'Sports Fitness Dumbbell Set 20kg', cat: 'sports', brand: 'puma', price: 3499, disc: 2499, img: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600' },
      { name: 'Canon EOS R50 Mirrorless Camera Body with 18-45mm Lens', cat: 'electronics', brand: 'canon', price: 65995, disc: 58995, img: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600' },
      { name: 'Nikon Z50 Mirrorless Camera Kit', cat: 'electronics', brand: 'nikon', price: 78995, disc: 69995, img: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600' },
      { name: 'Atomic Habits Hardcover Book by James Clear', cat: 'books', brand: 'aurastyle', price: 799, disc: 499, img: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600' },
      { name: 'LEGO Star Wars Millennium Falcon Building Set', cat: 'toys', brand: 'auratech', price: 14999, disc: 12999, img: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=600' },
      { name: 'Pampers All-round Protection Baby Diapers (Monthly Box)', cat: 'baby', brand: 'aurafresh', price: 2199, disc: 1699, img: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600' },
      { name: 'Pedigree Adult Dry Dog Food Chicken & Vegetables 10kg', cat: 'pet-supplies', brand: 'aurafresh', price: 2499, disc: 1999, img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600' },
      { name: 'Ergonomic Mesh High Back Office Chair', cat: 'office', brand: 'aurastyle', price: 9999, disc: 6999, img: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600' },
      { name: 'Solimo Car Dashboard Mobile Holder', cat: 'automotive', brand: 'auratech', price: 999, disc: 499, img: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=600' },
      { name: 'Ray-Ban Aviator Classic Sunglasses', cat: 'accessories', brand: 'aurastyle', price: 8990, disc: 7190, img: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600' },
      { name: 'American Tourister 3-Piece Hard Cabin Luggage Set', cat: 'travel', brand: 'aurastyle', price: 18999, disc: 11999, img: 'https://images.unsplash.com/photo-1565026057447-b8899f290906?w=600' },
      { name: '18K Yellow Gold Diamond Solitaire Ring', cat: 'jewellery', brand: 'titan', price: 49999, disc: 42999, img: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600' },
    ];

    for (let i = 0; i < 43; i++) {
      const template = extraCategories[i % extraCategories.length];
      products.push({
        id: `prod-${pId++}`,
        title: `${template.name} (Series ${i + 1})`,
        slug: `${template.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-series-${i + 1}`,
        description: `Premium grade ${template.name} crafted with top-tier materials and quality testing. Perfect for everyday usage.`,
        shortDescription: `High quality ${template.name} with original brand warranty.`,
        basePrice: template.price,
        discountPrice: template.disc,
        mrp: template.price,
        sku: `SKU-MKT-${template.cat.toUpperCase()}-${i + 100}`,
        isQuickCommerce: false,
        imageUrl: template.img,
        categorySlug: template.cat,
        brandSlug: template.brand,
        rating: 4.2 + (i % 8) * 0.1,
        reviewCount: 40 + i * 7,
        stock: 30 + i * 2,
        tags: [template.cat, template.brand, 'marketplace'],
      });
    }

    // ── 8. FLADO QUICK-COMMERCE PRODUCTS (60 Products) ────────────────────────
    const fladoItems = [
      { title: 'Fresh Farm Organic Bananas (1kg)', sub: 'Fruits & Vegetables', cat: 'groceries', brand: 'aurafresh', price: 80, disc: 59, img: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600', unit: 'kg', qty: 1 },
      { title: 'Red Delicious Apples (4 pcs / 500g)', sub: 'Fruits & Vegetables', cat: 'groceries', brand: 'aurafresh', price: 180, disc: 149, img: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600', unit: 'g', qty: 500 },
      { title: 'Fresh Hydroponic Tomatoes (500g)', sub: 'Fruits & Vegetables', cat: 'groceries', brand: 'aurafresh', price: 45, disc: 32, img: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600', unit: 'g', qty: 500 },
      { title: 'Amul Taaza Toned Milk (1 Litre Pouch)', sub: 'Milk & Dairy', cat: 'groceries', brand: 'amul', price: 54, disc: 54, img: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600', unit: 'L', qty: 1 },
      { title: 'Amul Pasteurized Salted Butter (100g Pack)', sub: 'Milk & Dairy', cat: 'groceries', brand: 'amul', price: 58, disc: 56, img: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600', unit: 'g', qty: 100 },
      { title: 'Britannia 100% Whole Wheat Bread (400g)', sub: 'Bread & Eggs', cat: 'groceries', brand: 'britannia', price: 50, disc: 45, img: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600', unit: 'g', qty: 400 },
      { title: 'Farm Fresh White Eggs (Pack of 12 Tray)', sub: 'Bread & Eggs', cat: 'groceries', brand: 'aurafresh', price: 110, disc: 92, img: 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?w=600', unit: 'pack', qty: 12 },
      { title: 'Lay’s India’s Magic Masala Potato Chips (50g)', sub: 'Snacks & Beverages', cat: 'groceries', brand: 'pepsi', price: 20, disc: 20, img: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600', unit: 'g', qty: 50 },
      { title: 'Coca-Cola Soft Drink Original Taste (750ml Bottle)', sub: 'Snacks & Beverages', cat: 'groceries', brand: 'coca-cola', price: 40, disc: 38, img: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600', unit: 'ml', qty: 750 },
      { title: 'Red Bull Energy Drink (250ml Can)', sub: 'Snacks & Beverages', cat: 'groceries', brand: 'red-bull', price: 125, disc: 119, img: 'https://images.unsplash.com/photo-1606851094655-b2593a9af63f?w=600', unit: 'ml', qty: 250 },
      { title: 'Dettol Original Germ Protection Handwash (200ml)', sub: 'Personal Care', cat: 'groceries', brand: 'dettol', price: 99, disc: 89, img: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600', unit: 'ml', qty: 200 },
      { title: 'Dove Deeply Nourishing Body Wash (250ml)', sub: 'Personal Care', cat: 'groceries', brand: 'dove', price: 249, disc: 199, img: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600', unit: 'ml', qty: 250 },
    ];

    for (let f = 0; f < 60; f++) {
      const item = fladoItems[f % fladoItems.length];
      products.push({
        id: `flado-${f + 1}`,
        title: `${item.title} ${f >= 12 ? `(Batch ${Math.floor(f / 12) + 1})` : ''}`,
        slug: `flado-${item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${f + 1}`,
        description: `Fresh, high quality ${item.title} delivered in 10 minutes via Flado Quick Commerce. Store temperature controlled.`,
        shortDescription: `10-Min Express Delivery via Flado Darkstore.`,
        basePrice: item.price,
        discountPrice: item.disc,
        mrp: item.price,
        sku: `SKU-FLADO-${f + 100}`,
        isQuickCommerce: true,
        imageUrl: item.img,
        categorySlug: item.cat,
        brandSlug: item.brand,
        rating: 4.7 + (f % 3) * 0.1,
        reviewCount: 120 + f * 12,
        stock: 50 + (f % 20) * 5,
        subCategory: item.sub,
        unitOfMeasure: item.unit as any,
        quantityPerPack: item.qty,
        tags: ['flado', 'quick-commerce', 'grocery', '10min'],
      });
    }

    return products;
  }

  // ── 9. MASTER REVIEWS DATA ──────────────────────────────────────────────────
  static getMasterReviews(): SeedReview[] {
    return [
      {
        productId: 'prod-1',
        customerName: 'Rahul Sharma',
        title: 'Outstanding Active Noise Cancellation!',
        comment: 'Upgraded from Gen 1 to Gen 2 with USB-C. The ANC is incredible on flights and the soundstage is crisp!',
        rating: 5,
        isVerifiedPurchase: true,
        helpfulCount: 42,
      },
      {
        productId: 'prod-1',
        customerName: 'Ananya Verma',
        title: 'Worth every rupee',
        comment: 'Seamless integration with my iPhone 15 and MacBook. Battery easily lasts all day.',
        rating: 5,
        isVerifiedPurchase: true,
        helpfulCount: 19,
      },
      {
        productId: 'prod-2',
        customerName: 'Vikram Mehta',
        title: 'Best over-ear headphones on the market',
        comment: 'Sony hit a home run with the XM5. Extremely lightweight and comfortable during long coding sessions.',
        rating: 5,
        isVerifiedPurchase: true,
        helpfulCount: 35,
      },
      {
        productId: 'flado-1',
        customerName: 'Priya Nair',
        title: 'Delivered in 8 minutes flat!',
        comment: 'Super fresh organic bananas. Package was in perfect condition. Flado is incredible.',
        rating: 5,
        isVerifiedPurchase: true,
        helpfulCount: 15,
      },
      {
        productId: 'flado-4',
        customerName: 'Karan Kapoor',
        title: 'Cold fresh milk every morning',
        comment: 'Super fast delivery before breakfast. Chilled milk pouch delivered safely.',
        rating: 5,
        isVerifiedPurchase: true,
        helpfulCount: 22,
      },
    ];
  }
}
